### ISSUE TITLE
Review Needed in Homelab.md file.

### ISSUE THREAD

**Issue by kal-nemi** [syth3/Cyber-Beginner-Resources#1]
### Only section with serial no. 1 is visible. It would be great if some content is added.

**Comment by syth3** [comment]
Thanks for the interest! Unfortunately, I have not filled out this page yet. It is on my to-do list

**Comment by kal-nemi** [comment]
Thank You! For the Roadmap as it is very helpful for a beginner.

**Comment by syth3** [comment]
So glad you were able to get value out of it! Out of curiosity, how did you find it?

**Comment by kal-nemi** [comment]
As I am a newbie to open source,  i was exploring my field of interest and resources that might help me get further, so the advance search option of GitHub landed me to your repository.😄

**Comment by syth3** [comment]
@kal-nemi The page has now been updated!
